# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('../sphinxext'))

import sphinx_material

# -- Project information -----------------------------------------------------

project = 'Flask Unchained'
copyright = '2018, Brian Cappello'
author = 'Brian Cappello'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = 'v0.7.9'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'chios.bolditalic',
    'sphinx_click.ext',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'sphinx_material',
    'm2r',
]

autodoc_member_order = 'bysource'
autosectionlabel_prefix_document = True
autosummary_generate = True
autoclass_content = 'class'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = '.rst'

# The master toctree document.
master_doc = 'table-of-contents'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '*/autosummary/*.rst']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_material'
html_theme_path = sphinx_material.html_theme_path()
html_context = sphinx_material.get_html_context()

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    'nav_title': 'Flask Unchained',
    'logo_icon': '&#8734',  # infinity
    # 'logo_icon': '&#931',  # sigma (sum)
    'base_url': 'http://localhost:8000/',

    'color_primary': 'blue',
    'color_accent': 'light-blue',

    'repo_url': 'https://github.com/briancappello/flask-unchained',
    'repo_name': 'Flask Unchained',

    'globaltoc_depth': 3,
    'globaltoc_collapse': True,
    'globaltoc_includehidden': False,

    'heroes': {
        '*': 'The quickest and easiest way to build large web apps and APIs with Flask',
    },
    # disable tabs below the hero
    'master_doc': False,
    'nav_links': [],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_context["css_files"] = [
    '_static/bolditalic.css',
    '_static/theme_customizations.css',
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
html_sidebars = {
    "**": ["logo-text.html", "globaltoc.html", "localtoc.html", "searchbox.html"]
}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'FlaskUnchaineddoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'FlaskUnchained.tex', 'Flask Unchained Documentation',
     'Brian Cappello', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'flaskunchained', 'Flask Unchained Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'FlaskUnchained', 'Flask Unchained Documentation',
     author, 'FlaskUnchained', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'click': ('https://click.palletsprojects.com/en/7.x/', None),
    'flask': ('http://flask.pocoo.org/docs/', None),
    'flask_admin': ('https://flask-admin.readthedocs.io/en/latest/', None),
    'flask_babelex': ('https://pythonhosted.org/Flask-BabelEx/', None),
    'flask_mail': ('https://pythonhosted.org/flask-mail/', None),
    'flask_marshmallow': (
        'https://flask-marshmallow.readthedocs.io/en/latest/', None),
    'flask_migrate': ('https://flask-migrate.readthedocs.io/en/latest/', None),
    'flask_session': ('https://pythonhosted.org/Flask-Session/', None),
    'flask_sqlalchemy': ('http://flask-sqlalchemy.pocoo.org/latest/', None),
    'flask_wtf': ('https://flask-wtf.readthedocs.io/en/stable/', None),
    'graphene_sqlalchemy': (
        'http://docs.graphene-python.org/projects/sqlalchemy/en/latest/', None),
    'marshmallow': ('https://marshmallow.readthedocs.io/en/stable/', None),
    'python': ('https://docs.python.org/3/', None),
    'sqlalchemy': ('https://docs.sqlalchemy.org/en/latest/', None),
    'werkzeug': ('http://werkzeug.pocoo.org/docs/0.14/', None),
}
