CONTROLLER_ROUTES_ATTR = '__fcb_controller_routes__'
FN_ROUTES_ATTR = '__fcb_fn_routes__'
NO_ROUTES_ATTR = '__fcb_no_routes__'
NOT_VIEWS_ATTR = '__fcb_not_views_method_names__'
REMOVE_SUFFIXES_ATTR = '__fcb_remove_suffixes__'
