CREATE = 'create'
DELETE = 'delete'
GET = 'get'
LIST = 'list'
PATCH = 'patch'
PUT = 'put'

RESOURCE_INDEX_METHODS = (LIST, CREATE)
RESOURCE_MEMBER_METHODS = (GET, DELETE, PATCH, PUT)
ALL_RESOURCE_METHODS = RESOURCE_INDEX_METHODS + RESOURCE_MEMBER_METHODS
