CREATE = 'create'
DELETE = 'delete'
GET = 'get'
LIST = 'list'
PATCH = 'patch'
PUT = 'put'

RESOURCE_INDEX_METHODS = {CREATE, LIST}
RESOURCE_MEMBER_METHODS = {DELETE, GET, PATCH, PUT}
ALL_RESOURCE_METHODS = RESOURCE_INDEX_METHODS | RESOURCE_MEMBER_METHODS
